"""
Pydantic data transfer objects for the Operations feature.

Defines request and response schemas for forecast, replenishment, and alert endpoints.
"""

from pydantic import BaseModel, Field
from typing import Any, Dict, List


class WeatherInput(BaseModel):
    """Input schema for manual weather condition override."""

    temperature_celsius: float = Field(
        ..., description="Ambient temperature in Celsius."
    )
    humidity_percentage: float = Field(
        ..., ge=0.0, le=100.0, description="Relative humidity percentage."
    )


class DispatchAction(BaseModel):
    """A recommended logistics dispatch action generated by the forecast engine."""

    action: str = Field(..., description="Action code (e.g., DISPATCH_WATER_TRUCK).")
    target_zone: str = Field(..., description="Topology node ID of the target zone.")
    quantity: int = Field(..., gt=0, description="Amount of resource to dispatch.")
    unit: str = Field(
        ..., description="Unit of the dispatched resource (e.g., Liters, Kits)."
    )
    volunteer_group: str = Field(
        ..., description="Volunteer group assigned to the dispatch."
    )


class OperationsAlert(BaseModel):
    """An operational alert generated when a resource threshold is breached."""

    severity: str = Field(..., description="Alert severity: CRITICAL or WARNING.")
    resource: str = Field(..., description="Name of the affected resource.")
    message: str = Field(..., description="Human-readable alert description.")


class ForecastResponse(BaseModel):
    """Full operations forecast payload including heat metrics, alerts, and dispatch actions."""

    heat_index_celsius: float = Field(
        ..., description="Calculated heat index in Celsius."
    )
    heat_index_fahrenheit: float = Field(
        ..., description="Calculated heat index in Fahrenheit."
    )
    danger_level: str = Field(..., description="Heat danger classification string.")
    consumption_rates: Dict[str, float] = Field(
        ..., description="Per-hour resource consumption rates."
    )
    remaining_time_hours: Dict[str, float] = Field(
        ..., description="Estimated hours until depletion per resource."
    )
    depletion_percentages: Dict[str, float] = Field(
        ..., description="Current depletion percentage per resource."
    )
    alerts: List[OperationsAlert] = Field(
        default_factory=list, description="Active operational alerts."
    )
    dispatch_actions: List[DispatchAction] = Field(
        default_factory=list, description="Recommended automated dispatch actions."
    )
    inputs: Dict[str, Any] = Field(
        ..., description="Weather and attendance inputs used for this forecast."
    )


class ReplenishResponse(BaseModel):
    """Response returned after a successful supply replenishment action."""

    status: str = Field(..., description="Replenishment status: 'success'.")
    message: str = Field(..., description="Human-readable confirmation message.")
